import 'dart:typed_data';

abstract interface class ISapObject {
  int get handle;

  bool get isValid => handle != 0;
  bool get isInvalid => handle == 0;

  String get id;
  String get name;
  String get type;
  int get typeAsNumber;
  bool get containerType;
  String get text;
  set text(String v);
  String get tooltip;
  String get iconName;
  bool get changeable;
  bool get modified;
  set modified(bool value);
  int get width;
  int get height;
  int get left;
  int get top;
  set top(int value);
  void add(String item);
  ISapObject? get parent;
  ISapObject? get children;
  int get count;
  ISapObject? item(int index);
  ISapObject? elementAt(int index);
  ISapObject? get activeSession;
  ISapObject? get activeWindow;
  ISapObject? get info;
  bool get busy;
  String get systemName;
  String get client;
  String get user;
  String get language;
  String get transaction;
  String get program;
  int get screenNumber;
  int get responseTime;
  ISapObject? get accLabelCollection;
  String get accText;
  String get accTextOnRequest;
  String get accTooltip;
  String get defaultTooltip;
  int get screenLeft;
  int get screenTop;
  bool get isSymbolFont;
  ISapObject? get parentFrame;
  ISapObject? get connections;
  String get connectionErrorText;
  ISapObject? get utils;
  bool get allowSystemMessages;
  set allowSystemMessages(bool v);
  bool get buttonbarVisible;
  set buttonbarVisible(bool v);
  bool get statusbarVisible;
  set statusbarVisible(bool v);
  bool get titlebarVisible;
  set titlebarVisible(bool v);
  bool get toolbarVisible;
  set toolbarVisible(bool v);
  bool get historyEnabled;
  set historyEnabled(bool v);
  bool get selected;
  set selected(bool v);
  bool get fixed;
  int get majorVersion;
  int get minorVersion;
  int get patchlevel;
  int get revision;
  bool get newVisualDesign;
  String get connectionString;
  String get description;
  bool get disabledByServer;
  ISapObject? get sessions;
  ISapObject? get errorList;
  bool get isListAdapter;
  String get passport;
  set passport(String v);
  String get recordFile;
  set recordFile(String v);
  bool get recording;
  set recording(bool v);
  int get testToolMode;
  set testToolMode(int v);
  String get applicationServer;
  int get flushes;
  String get group;
  int get guiCodepage;
  bool get isLowSpeedConnection;
  String get messageServer;
  int get roundTrips;
  bool get scriptingModeReadOnly;
  int get sessionNumber;
  int get systemNumber;
  String get systemSessionId;
  String get uiGuideline;
  String get accDescription;
  bool get dragDropSupported;
  int get shellHandle;
  ISapObject? get ocxEvents;
  String get subType;
  int get chartCount;
  bool get elementVisualizationMode;
  set elementVisualizationMode(bool v);
  ISapObject? get guiFocus;
  bool get iconic;
  ISapObject? get systemFocus;
  int get workingPaneHeight;
  int get workingPaneWidth;
  ISapObject? get rows;
  ISapObject? get verticalScrollbar;
  int get rowCount;
  int get visibleRowCount;
  int get currentCol;
  int get currentRow;
  int get gridColumnCount;
  int get gridRowCount;
  int get caretPosition;
  set caretPosition(int v);
  String get displayedText;
  int get maxLength;
  bool get numerical;
  int get focusedHorizontalSash;
  int get focusedVerticalSash;
  bool get isVertical;
  String get rowText;
  int get charHeight;
  int get charLeft;
  int get charTop;
  int get charWidth;
  int get colorIndex;
  bool get colorIntensified;
  bool get colorInverse;
  bool get highlighted;
  bool get isHotspot;
  bool get isLeftLabel;
  bool get isRightLabel;
  bool get isListElement;
  String getCellListBoxCurIndex(int row, String column);
  String getColumnOperationType(String column);
  String getColumnSortType(String column);
  String getColumnTotalType(String column);
  String getColorInfo(int color);
  int getRowTotalLevel(int row);
  String getSymbolInfo(String symbol);
  bool getToolbarButtonChecked(int buttonPos);
  bool getButtonChecked(int buttonPos);
  String getToolbarButtonIcon(int buttonPos);
  String getToolbarButtonTooltip(int buttonPos);
  String getToolbarButtonType(int buttonPos);
  int getToolbarFocusButton();
  bool isTotalRowExpanded(int row);
  String historyCurEntry(int row, String column);
  int historyCurIndex(int row, String column);
  bool historyIsActive(int row, String column);
  List<String>? getColumnTitles(String column);
  ISapObject? historyList(int row, String column);
  bool getButtonEnabled(int buttonPos);
  String getButtonIcon(int buttonPos);
  String getButtonId(int buttonPos);
  String getButtonText(int buttonPos);
  String getButtonTooltip(int buttonPos);
  String getButtonType(int buttonPos);
  String getMenuItemIdFromPosition(int pos);
  void pressButtonToolBarControl(String id);
  void pressContextButton(String id);
  void selectMenuItem(String id);
  void selectMenuItemByText(String text);
  int get buttonCount;
  int get focusedButton;
  String get selectionMode;
  int get toolbarButtonCount;
  String get firstVisibleColumn;
  set firstVisibleColumn(String value);
  int get firstVisibleRow;
  set firstVisibleRow(int value);
  int get frozenColumnCount;
  List<String>? get selectedCells;
  set selectedCells(List<String> cells);
  List<String>? get selectedColumns;
  set selectedColumns(List<String> columns);
  String getListProperty(String property);
  String getListPropertyNonRec(String property);
  ISapObject? findById(String id);
  void press();
  void select();
  void sendVKey(int vkey);
  ISapObject? getCell(int row, int col);
  void resizeWorkingPane(int width, int height, bool throwOnFail);
  void resizeWorkingPaneEx(int width, int height, bool throwOnFail);
  void clearSelection();
  void clickCurrentCell();
  void closeConnection();
  void closeSession(String id);
  void createSession();
  void doubleClickCurrentCell();
  void endTransaction();
  void startTransaction(String tcode);
  void contextMenu();
  void currentCellMoved();
  void pressEnter();
  void pressF1();
  void pressF4();
  void pressButtonCurrentCell();
  void pressTotalRowCurrentCell();
  void selectAll();
  void selectionChanged();
  void triggerModified();
  void setFocus();
  int visualize(bool on, String innerObject);
  ISapObject? dumpState(String innerObject);
  ISapObject? findByName(String name, String type);
  ISapObject? findAllByName(String name, String type);
  ISapObject? findByNameEx(String name, int typeAsNumber);
  ISapObject? findAllByNameEx(String name, int typeAsNumber);
  void deleteRows(String rows);
  void duplicateRows(String rows);
  void insertRows(String rows);
  void deselectColumn(String col);
  void selectColumn(String col);
  void pressColumnHeader(String col);
  void pressToolbarButton(String id);
  void pressToolbarContextButton(String id);
  void selectToolbarMenuItem(String id);
  void click(int row, String col);
  void doubleClick(int row, String col);
  void pressTotalRow(int row, String col);
  void setCurrentCell(int row, String col);
  void setColumnWidth(String col, int width);
  void modifyCell(int row, String col, String value);
  void modifyCheckBox(int row, String col, bool checked);
  void moveRows(int from, int to, int dest);
  String getCellValue(int row, String col);
  String getCellIcon(int row, String col);
  String getCellState(int row, String col);
  String getCellTooltip(int row, String col);
  String getCellType(int row, String col);
  String getCellHotspotType(int row, String col);
  int getCellColor(int row, String col);
  int getCellHeight(int row, String col);
  int getCellWidth(int row, String col);
  int getCellLeft(int row, String col);
  int getCellTop(int row, String col);
  int getCellMaxLength(int row, String col);
  int getCellListBoxCount(int row, String col);
  int barCount(int chartId);
  String getBarContent(int chartId, int barId, int textId);
  String getGridLineContent(int chartId, int gridlineId, int lineId);
  int gridCount(int chartId);
  int linkCount(int chartId);
  void sendData(String data);
  bool getCellChangeable(int row, String col);
  bool getCellCheckBoxChecked(int row, String col);
  bool hasCellF4Help(int row, String col);
  bool isCellHotspot(int row, String col);
  bool isCellSymbol(int row, String col);
  bool isCellTotalExpander(int row, String col);
  String getColumnDataType(String col);
  String getColumnTooltip(String col);
  String getDisplayedColumnTitle(String col);
  int getColumnPosition(String col);
  bool isColumnFiltered(String col);
  bool isColumnKey(String col);
  String getToolbarButtonId(int pos);
  String getToolbarButtonText(int pos);
  bool getToolbarButtonEnabled(int pos);
  ISapObject? openConnection(
    String description, {
    bool sync = true,
    bool raise = true,
  });
  ISapObject? openConnectionByConnectionString(
    String connectString, {
    bool sync = true,
    bool raise = true,
  });
  bool addHistoryEntry(String fieldName, String value);
  bool dropHistory();
  ISapObject? createGuiCollection();
  bool registerROT();
  void revokeROT();
  void ignore(int windowHandle);
  bool get emphasized;
  ISapObject? get leftLabel;
  ISapObject? get rightLabel;
  void selectContextMenuItem(String functionCode);
  void selectContextMenuItemByPosition(String positionDesc);
  void selectContextMenuItemByText(String text);
  void collapseNode(String nodeKey);
  void expandNode(String nodeKey);
  void doubleClickNode(String nodeKey);
  void selectNode(String nodeKey);
  void unselectNode(String nodeKey);
  void nodeContextMenu(String nodeKey);
  void headerContextMenu(String headerName);
  void pressKey(String key);
  void clickLink(String nodeKey, String itemName);
  void doubleClickItem(String nodeKey, String itemName);
  void pressButton(String nodeKey, String itemName);
  void selectItem(String nodeKey, String itemName);
  void ensureVisibleHorizontalItem(String nodeKey, String itemName);
  void itemContextMenu(String nodeKey, String itemName);
  void changeCheckbox(String nodeKey, String itemName, bool checked);
  void defaultContextMenu();
  void unselectAll();
  void close();
  void maximize();
  void iconify();
  void restore();
  void jumpBackward();
  void jumpForward();
  void tabBackward();
  void tabForward();
  int compBitmap(String filename1, String filename2);
  String hardCopy(String filename);
  String getItemText(String key, String name);
  String getNodeTextByKey(String key);
  String getNodeTextByPath(String path);
  bool getCheckBoxState(String nodeKey, String itemName);
  bool isFolder(String nodeKey);
  bool isFolderExpandable(String nodeKey);
  bool isFolderExpanded(String nodeKey);
  bool isVKeyAllowed(int vKey);
  int getTreeType();
  List<String>? getAllNodeKeys();
  List<String>? getSelectedNodes();
  List<String>? getColumnNames();
  List<String>? getColumnHeaders();
  void pressButtonInGrid(int row, String column);
  List<String>? get columnOrder;
  set columnOrder(int collectionHandle);
  int get length;
  int get hierarchyHeaderWidth;
  set hierarchyHeaderWidth(int value);
  String get selectedNode;
  set selectedNode(String value);
  String get topNode;
  set topNode(String value);
  int get columnCount;
  String get title;
  int get currentCellRow;
  set currentCellRow(int v);
  String get currentCellColumn;
  set currentCellColumn(String v);
  String get selectedRows;
  set selectedRows(String v);
  void configureLayout();
  void deselectAllColumns();
  ISapObject? getAbsoluteRow(int index);
  void reorderTable(String permutation);
  void selectAllColumns();
  int get colSelectMode;
  dynamic get columns;
  ISapObject? get horizontalScrollbar;
  int get rowSelectMode;
  String get tableFieldName;
  int get maximum;
  int get minimum;
  int get pageSize;
  int get range;
  int get position;
  set position(int value);
  String get historyCurEntryProp;
  int get historyCurIndexProp;
  bool get historyIsActiveProp;
  bool get isOField;
  bool get required;
  bool get flushing;
  int get groupCount;
  int get groupPos;
  List<String>? get historyListProp;
  ISapObject? get groupMembers;
  void release();
  Uint8List hardCopyToMemory();
  int showMessageBox(String title, String text, int msgIcon, int msgType);
  String getObjectTree(String id, {List<String> properties = const []});
  bool get isActive;
  bool get accEnhancedTabChain;
  set accEnhancedTabChain(bool v);
  bool get accSymbolReplacement;
  set accSymbolReplacement(bool v);
  int get progressPercent;
  String get progressText;
  bool get isListBoxActive;
  int get listBoxCurrEntry;
  int get listBoxCurrEntryHeight;
  int get listBoxCurrEntryLeft;
  int get listBoxCurrEntryTop;
  int get listBoxCurrEntryWidth;
  int get listBoxHeight;
  int get listBoxLeft;
  int get listBoxTop;
  int get listBoxWidth;
  String get passportPreSystemId;
  set passportPreSystemId(String v);
  String get passportSystemId;
  set passportSystemId(String v);
  String get passportTransactionId;
  set passportTransactionId(String v);
  bool get record;
  set record(bool v);
  bool get saveAsUnicode;
  set saveAsUnicode(bool v);
  bool get showDropdownKeys;
  set showDropdownKeys(bool v);
  bool get suppressBackendPopups;
  set suppressBackendPopups(bool v);
  void sendCommand(String command);
  void sendCommandAsync(String command);
  void clearErrorList();
  void enableJawsEvents();
  void lockSessionUI();
  void unlockSessionUI();
  String asStdNumberFormat(String number);
  String getIconResourceName(String iconText);
  String getVKeyDescription(int vkey);
  List<String>? findByPosition(int x, int y, {bool raise = true});
  bool get opened;
  bool get isPopupDialog;
  set isPopupDialog(bool value);
  String get popupDialog;
  set popupDialog(String value);
  String get helpButtonHelpText;
  String get helpButtonText;
  String get messageText;
  int get messageType;
  String get okButtonText;
  bool get visible;
  set screenLeft(int value);
  set screenTop(int value);
  ISapObject? findByLabel(String text, String type);
  void listNavigate(String navType);
  bool get isOTFPreview;
  bool get selectable;
  void scrollToLeft();
  ISapObject? get leftTab;
  ISapObject? get selectedTab;
  void createSupportMessageClick();
  void doubleClickNoArgs();
  void serviceRequestClick();
  bool get messageAsPopup;
  int get messageHasLongText;
  String get messageId;
  String get messageNumber;
  String get messageParameter;
  String get messageTypeRetunString;
  void contextMenuCalendar(
    int ctxMenuId,
    int ctxMenuCellRow,
    int ctxMenuCellCol,
    String dateBegin,
    String dateEnd,
  );
  void setKeySpace();
  ISapObject? get curListBoxEntry;
  ISapObject? get listBoxEntries;
  ISapObject? get entries;
  String get key;
  set key(String value);
  int get pos;
  String get value;
  bool get showKey;
  set value(String newValue);
  void fireSelected();
  String get labelText;
  String get selectedInComboBox;
  set selectedInComboBox(String value);
  void valueChange(
    int series,
    int point,
    String xValue,
    String yValue,
    bool dataChange,
    String id,
    String zValue,
    int changeFlag,
  );
  void changeSelection(int indexPosition);
  bool get dockerIsVertical;
  int get dockerPixelSize;
  void annotationTextRequest(String strText);
  bool get annotationEnabled;
  set annotationEnabled(bool value);
  int get annotationMode;
  set annotationMode(int value);
  String get redliningStream;
  set redliningStream(String value);
  int getBrowerControlType();
  void sapEvent(String frameName, String postData, String url);
  Object? get browserHandle;
  int get documentComplete;
  void submit();
  String get buttonTooltip;
  bool get findButtonActivated;
  String get historyCurEntryFromInputFieldControl;
  int get historyCurIndexFromInputFieldControl;
  bool get historyIsActiveFromInputFieldControl;
  String get promptText;
  String getLinkContent(int linkId, int textId);
  String getNodeContent(int nodeId, int textId);
  int get linkCountProperty;
  int get nodeCount;
  void appendRow(String name, String row);
  void closeDocument(int cookie, bool everChanged, bool changedAfterSave);
  void customEvent(
    int cookie,
    String eventName,
    int paramCount, [
    String? p1,
    String? p2,
    String? p3,
    String? p4,
    String? p5,
    String? p6,
    String? p7,
    String? p8,
    String? p9,
    String? p10,
    String? p11,
    String? p12,
  ]);
  void removeContent(String name);
  void saveDocument(int cookie, bool changed);
  void setDocument(int index, String document);
  Object? get document;
  int get hostedApplication;
  void clickInPicture();
  void clickControlArea(int x, int y);
  void clickPictureArea(int x, int y);
  void contextMenuInPicture(int x, int y);
  void doubleClickInPicture();
  void doubleClickControlArea(int x, int y);
  void doubleClickPictureArea(int x, int y);
  String get altText;
  String get displayMode;
  String get icon;
  String get url;
  bool get isStepLoop;
  bool get isStepLoopInTableStructure;
  int get loopColCount;
  int get loopCurrentCol;
  int get loopCurrentColCount;
  int get loopCurrentRow;
  int get loopRowCount;
  int getColSize(int id);
  int getRowSize(int id);
  void setColSize(int id, int size);
  void setRowSize(int id, int size);
  int get isVerticalInt;
  int get sashPosition;
  set sashPosition(int value);
  void contextMenuInStage(String strId);
  void doubleClickInStage(String strId);
  void selectItemsInStage(String strItems);
  String getLineText(int nLine);
  String getUnprotectedTextPart(int part);
  bool isBreakpointLine(int nLine);
  bool isCommentLine(int nLine);
  bool isHighlightedLine(int nLine);
  bool isProtectedLine(int nLine);
  bool isSelectedLine(int nLine);
  void modifiedStatusChanged(bool status);
  void multipleFilesDropped();
  void setSelectionIndexes(int start, int end);
  bool setUnprotectedTextPart(int part, String text);
  void singleFileDropped(String filename);
  int get currentColumn;
  int get currentLine;
  int get firstVisibleLine;
  set firstVisibleLine(int value);
  int get lastVisibleLine;
  int get lineCount;
  int get numberOfUnprotectedTextParts;
  String get selectedText;
  int get selectionEndColumn;
  int get selectionEndLine;
  int get selectionIndexEnd;
  int get selectionIndexStart;
  int get selectionStartColumn;
  int get selectionStartLine;
  void closeFile(int file);
  int openFile(String filename);
  void write(int file, String text);
  void writeLine(int file, String text);
  int get messageOptionOk;
  int get messageOptionOkCancel;
}
